### ISSUE TITLE
Setting CFProcessPath breaks Desktop.getDesktop().open

### ISSUE THREAD

**Issue by jlholt** [tofi86/universalJavaApplicationStub#10]
If I don't set CFProcessPath, then I cannot drag items onto the application's dock icon for processing. If I do set CFProcessPath, then the application cannot open files associated with other applications (e.g., the application's user guide is a pdf). I need to be able to both (a) drag to the dock icon and (b) consistently have the desktop open an arbitrary file associated with an arbitrary application.

Here is the content of test.java.

```
import java.io.*;
import java.awt.Desktop;

public class test {
    public static void main (String args[]) throws IOException {
        Desktop.getDesktop().open(new File("a resource filename associated with Preview or MacVim"));
    }
}
```

Here is the content of my pared down version of JavaApplicationStub.

```
#!/bin/sh
PGMDIR=`dirname "$0"`
cd "$PGMDIR"/../../
AppPackageFolder=`pwd`
ResourcesFolder="$AppPackageFolder/Contents/Resources"
JAVACMD=/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java
CFProcessPath="$0"
export CFProcessPath
cd "$ResourcesFolder"
exec $JAVACMD -cp "Java/test.jar" test
```

Here is the content of the build.xml file.

```
<?xml version="1.0" ?>
<project name="test" default="dist" basedir=".">
  <target name="dist">
      <javac srcdir="." destdir="." includeAntRuntime="false" />
      <jar destfile="test.jar" basedir="." includes="test.class" />
      <taskdef name="jarbundler" classname="net.sourceforge.jarbundler.JarBundler"
          classpath="jarbundler.jar" />
      <mkdir dir="release" />
      <jarbundler dir="release" name="test" mainclass="test" jar="test.jar" />
      <delete file="release/test.app/Contents/MacOS/JavaApplicationStub"/>
      <copy file="JavaApplicationStub" todir="release/test.app/Contents/MacOS"/>
      <chmod file="release/test.app/Contents/MacOS/JavaApplicationStub" perm="755" />
      <copy file="onelineoftext.txt" todir="release/test.app/Contents/Resources"/>
  </target>
</project>
```

And here is how I build and run the application.

```
$ ant
$ open release/test.app
```

If you _DO NOT_ comment out the setting for CFProcessPath in the stub, then filename will be opened only if Preview or MacVim are already running. If you _DO_ comment out the setting of CFProcessPath, then filename will always be opened regardless of the running state of the associated application. I discovered that if filename is associated with Adobe Reader, then the file is always opened even if I _DO_ set CFProcessPath. It's special but I don't know why.

I'm using Mac OS X Yosemite (10.10.1) and here are my java homes.

```
$ /usr/libexec/java_home -V
Matching Java Virtual Machines (4):
    1.7.0_71, x86_64:   "Java SE 7" /Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home
    1.7.0_40, x86_64:   "Java SE 7" /Library/Java/JavaVirtualMachines/jdk1.7.0_40.jdk/Contents/Home
    1.6.0_65-b14-466.1, x86_64: "Java SE 6" /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
    1.6.0_65-b14-466.1, i386:   "Java SE 6" /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home
```

Altering the version of Java does not alter the behavior.

**Comment by tofi86** [comment]
This sounds really strange...
Will have a look in the next couple of days/weeks...

However, I will not remove `export CFProcessPath="$0"` as this deliviers Drag&Drop functionality and therefore is substantial to the stub...

**Comment by jlholt** [comment]
Yes, it's quite frustrating because my app is broken one way or the other. I either cannot drag&drop or I cannot open files.

**Comment by tofi86** [comment]
*Note:* This has also been discussed for the Eclipse Launcher in
* https://boga.wordpress.com/2006/01/22/eclipse-launcher/
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=53260#c46

> It works, but someone has to kill the CFProcessPath variable after eclipse started otherwise all programs started from eclipse will be behaving like it has the Eclipse.app location.

Their solution is to `unset` the `CFProcessPath` environment variable after having started eclipse.
Without trying I'd assume this would still break our Drag&Drop feature to the dock icon then...

**Comment by Dylan-M** [comment]
I'm wondering what the actual exception that is thrown is? I know your method in the test app throws an ioexception, but that isn't really helpful since the open command can throw 4 or 5 different exceptions. Could you maybe wrap it in a try/catch and have the catch write to System.out.println with the actual exception?

Also, in the meantime... here's a great work-around [accepted answer], since getDesktop.open fails quite a lot on Linux at the very least, and maybe permanent solution:
http://stackoverflow.com/questions/18004150/desktop-api-is-not-supported-on-the-current-platform

**Comment by Dylan-M** [comment]
Per the Swing ( https://docs.oracle.com/javase/tutorial/uiswing/misc/desktop.html ) tutorial, the OP's code is wrong anyway, because it doesn't test `Desktop.isDesktopSupported()` before calling `Desktop.getDesktop()`.

Additionally, even when `isDesktopSupported()` returns true, it doesn't mean that every subcomponent returns true. Each of them should be tested, a'la:

    /**
    * Enable actions that are supported on this host.
    * The actions are the following: open browser, 
    * open email client, and open, edit, and print
    * files using their associated application.
    */
    private void enableSupportedActions() {
        if (desktop.isSupported(Desktop.Action.BROWSE)) {
            txtBrowserURI.setEnabled(true);
            btnLaunchBrowser.setEnabled(true);
        }
        
        if (desktop.isSupported(Desktop.Action.MAIL)) {
            txtMailTo.setEnabled(true);
            btnLaunchEmail.setEnabled(true);
        }

        if (desktop.isSupported(Desktop.Action.OPEN)) {
            rbOpen.setEnabled(true);
        }
        if (desktop.isSupported(Desktop.Action.EDIT)) {
            rbEdit.setEnabled(true);
        }
        if (desktop.isSupported(Desktop.Action.PRINT)) {
            rbPrint.setEnabled(true);
        }
        
        if (rbEdit.isEnabled() || rbOpen.isEnabled() || rbPrint.isEnabled()) {
            txtFile.setEnabled(true);
            btnLaunchApplication.setEnabled(true);
        }
    }

I would personally close this as wont-fix and redirect users to the proper way to do things (ie, check if this is supported and if it isn't _work around it_ in code as the accepted answer on SO does)

References:
https://stackoverflow.com/questions/18004150/desktop-api-is-not-supported-on-the-current-platform
https://docs.oracle.com/javase/tutorial/uiswing/misc/desktop.html

**Comment by magnusviri** [comment]
I have a similar issue.  I am launching ImageJ with Java 6 on 10.14 Mojave, and I have to launch it in 32-bit mode ("arch -i386").  ImageJ works fine.  But I have a 32-bit plugin that grabs an image from a Scion camera and it crashes.  When I comment out `export CFProcessPath="$0"` it runs fine.  But ImageJ's drag-and-drop no longer works.  I tried various things and couldn't get around this.

**Comment by tofi86** [comment]
I have no solution for this. Closing as `wontfix`.
