### ISSUE TITLE
WorkingDirectory not set correctly to USER_HOME

### ISSUE THREAD

**Issue by mbtaylor** [tofi86/universalJavaApplicationStub#11]
If I have the following in the Info.plist:

    <key>WorkingDirectory</key>
    <string>$USER_HOME</string>

I (well, one of my users) see this error message in the startup log:

    /Applications/VO-tools/topcat-4.2-2/TOPCAT.app/Contents/MacOS/TopcatUJAStub: line 258: cd: ~: No such file or directory

I think the problem is the quotes round the tilde character in the WorkingDirectory assignment here:

           elif [ "${JVMWorkDir}" == "\$USER_HOME" ]; then
                WorkingDirectory="~"

but it's hard for me to test it because I don't have a Mac myself.  Is this feature believed working as it stands?  Can somebody try it out and, if it's a bug, fix it?  Thanks!

**Comment by jlholt** [comment]
I am able to reproduce your problem on my MacBookPro running Yosemite. You are correct that if the assignment is coded as
    WorkingDirectory=~
then the stub will be able to cd correctly. It will also work if the ~ is replaced with $HOME.

**Comment by tofi86** [comment]
Thanks for reporting this issue.
At the moment, I can't test this, but I think I remember that I put it in quotes to avoid issues with blanks in path names.
writing this, i'm wondering if OS X even allows spaces in usernames - my mac stripped the space during setup...

However, looking at [line 148](https://github.com/tofi86/universalJavaApplicationStub/blob/master/src/universalJavaApplicationStub#L148) we got a similar situation with an inconsistency in the script. There I used the tilda as well - but with an `eval echo` to expand the path name first:
```
	USER_HOME="`eval echo ~`"
```

Could you please check the following and see if it works if you change line 131 ff. to the following:

```
	elif [ "${JVMWorkDir}" == "\$USER_HOME" ]; then
		WorkingDirectory="`eval echo ~`"
```

**Comment by jlholt** [comment]
You don't need to worry about blanks. I didn't say so in my previous post
but I did test what happens when my home directory setting contains blanks.
It works fine. You simply need to remove the quotes as in...

WorkingDirectory=~

**Comment by tofi86** [comment]
Going to use the environment variable `$HOME` in the future. bugfix is on the way...
