### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by israelins85** [tofi86/universalJavaApplicationStub#115]
I'm submitting a translation:

# Brazilian Portuguese
pt)
	MSG_ERROR_LAUNCHING="ERRO iniciando '${CFBundleName}'."
	MSG_MISSING_MAINCLASS="'MainClass' não foi definida!\nA aplicação java não poderá ser iniciada!"
	MSG_JVMVERSION_REQ_INVALID="A sintaxe da versão Java requerida não é valida: %s\nPor favor contacte o desenvolvedor dessa aplicação."
	MSG_NO_SUITABLE_JAVA="Não foi encontrado uma versão Java compatível no seu sistema!\nEsta aplicação precisa do Java %s"
	MSG_JAVA_VERSION_OR_LATER="ou maior"
	MSG_JAVA_VERSION_LATEST="(última atualização)"
	MSG_JAVA_VERSION_MAX="máxima %s"
	MSG_NO_SUITABLE_JAVA_CHECK="Verifique se instalou a versão Java necessária."
	MSG_INSTALL_JAVA="Você precisa instalar o JAVA no seu Mac!\nPor favor, visite java.com para instruções de instalação..."
	MSG_LATER="Depois"
	MSG_VISIT_JAVA_DOT_COM="Java por Oracle"
	MSG_VISIT_ADOPTOPENJDK="Java por AdoptOpenJDK"
    ;;

**Comment by israelins85** [comment]
Many of the words are the same, but I don't know If that's the case.

**Comment by tofi86** [comment]
Thank you for your contribution, @israelins85 👏 🎉 

On `develop` branch I added support for country specific locales such as `pt-BR` (previously only the "language" part like `pt` was supported) and added your Brasilian Portugues translation.

Go ahead and try the dev version and see if it works for you! Let me know if anything doesn't work as expected.
