### ISSUE TITLE
adding embedded JVM key into demo plist (failed) 

### ISSUE THREAD

**Issue by ivanooi** [tofi86/universalJavaApplicationStub#116]
Hi, 

  I added the embedded JVM key into demo plist. but look like it did not work. I'm having this error. 

Mac OS 10.15
JDK 16

![image](https://user-images.githubusercontent.com/15061028/146632451-4b18389f-fafd-46e3-a2a5-2912edd4e8a8.png)
![image](https://user-images.githubusercontent.com/15061028/146632578-98c2969f-447c-47d3-b90b-c20bd68c3d73.png)

this is how the plist look like : 
![image](https://user-images.githubusercontent.com/15061028/146632481-006fb762-5203-4d27-8c4a-2efbd23458a5.png)

this is where I place the vm : 
![image](https://user-images.githubusercontent.com/15061028/146632523-9482e701-5ac3-4184-b667-0da5649c602f.png)

Thanks for the great job :-D.

**Comment by ivanooi** [comment]
ooooo ! my bad!! the JVMVersion causing it failed. sorry 

it work now :-D.

**Comment by tofi86** [comment]
Glad to hear this works for you! :-)

**Comment by ivanooi** [comment]
Hi, is it possible to pass the parameters in? thanks

**Comment by tofi86** [comment]
Which params? The JAVA_HOME value? That's not possible...

**Comment by ivanooi** [comment]
pass abc into mac app
some things like this : 
my.app abc

**Comment by tofi86** [comment]
That should be possible, yes...

**Comment by ivanooi** [comment]
great! thanks :-D
