### ISSUE TITLE
Unable to get JFileChooser working despite using binary nor entitlements nor info.plist

### ISSUE THREAD

**Issue by AstroPixelProcessor** [tofi86/universalJavaApplicationStub#121]
I'm submitting a…

- [ X ] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**

Unable to get JFileChooser working in Documents folder despite using binary universalJavaApplicationStub nor code sign entitlements nor info.plist

**What is the expected behavior?**

A working application after installation with DMG that has your universalJavaApplicationStub

**What is the current behavior?**

JFileChooser is not showing files in Documents, Downloads etc.... depsite using a binary universalJavaApplicationStub downloaded from your  https://github.com/tofi86/universalJavaApplicationStub/releases/ for macOS 11.0.1 
I used all the signing entitlements possble i.c.m with hardened runtime and sandboxing, I need this to work with code signing and notarization and it seems to be not possible.

Hardened runtime is required for notarization to pass, so I added the runtime exceptions entitlements listed here: 
https://developer.apple.com/documentation/security/hardened_runtime
(only did not use the debugging one)

To be able to get access to files in Documents the way it should, I enabled sandboxing. This alone already prevents the application from starting in my case.

The File Access entitlements were added alongside sandboxing but it does not seem to work this way:
https://developer.apple.com/documentation/security/app_sandbox

Do you have any clue why it is not working? Should your universalJavaApplicationStub work with code signing with hardened runtime and notarization passing ? 

Without sandboxing, my application will pass notarization  and will start, but it will never offer me to get access to files in Documents depsite using the binary version of your stub in my application package. In your Readme it is more or less stated that that should do it, but not in my case.

**Please tell us about your environment:**

- universalJavaApplicationStub version: 3.2
- macOS version: 11.0.1 on M1 hardware aarch64
- Java version(s): Temurin openJKD  17

**Comment by AstroPixelProcessor** [comment]
Issue can be closed, sorry for opening it prematurely.

It turned out that I was not properly using the compiled universalJavaApplicationStub version in my DMG packaging to make it work. 

So now I have it working with a correctly functioning JFileChooser with a binary universalJavaApplicationStub in the .app package. Working on both intel and arm macs.

Bug completely on my side !

Thanks for your work ;-)

**Comment by tofi86** [comment]
Glad to hear it works!
