### ISSUE TITLE
JVMVersion in plist is ignored

### ISSUE THREAD

**Issue by Dylan-M** [tofi86/universalJavaApplicationStub#13]
Currently the JVMVersion tag [present in Apple info.plist, not sure about Oracle style] is being ignored.
I added the following in one of the general definition sections at the top of the file:
```BASH
# set the default JVM Version to a null string
JVMVersion=""
```
I've added the following code to the apple plist section:
```BASH
	# read the Java version we want to find
	JVMVersion=`/usr/libexec/PlistBuddy -c "print :Java:JVMVersion" "${InfoPlistFile}" 2> /dev/null | xargs`
	if [ "${JVMVersion}" != "" ]; then
		JVMVersion="-v "${JVMVersion}
	fi
```

And finally I modified the following in the find java section
```BASH
# otherwise check "/usr/libexec/java_home" symlinks
elif [ -x /usr/libexec/java_home ] && [ -d "`/usr/libexec/java_home ${JVMVersion} 2> /dev/null`" ] ; then
	JAVACMD="`/usr/libexec/java_home ${JVMVersion} 2> /dev/null`/bin/java"
```

And everything works kosher for me! If I exclude this, java_home still points to Apple's JDK6, but if I include it then it correctly points to my installed JDK8

**Comment by tofi86** [comment]
Yes, this is currently unsupported as stated in [Missing Features](https://github.com/tofi86/universalJavaApplicationStub#missing-features).

But thanks for trying and and the code contribution.
Will see whether I'll find the time to test & merge in the next couple of weeks...

**Comment by Dylan-M** [comment]
Aye, it's working great for me and the few people who've beta tested it for me. This combined with the other report I made are both working without complaint from my play testers so far.

**Comment by Dylan-M** [comment]
Just as an update, the project I'm on has pushed my updated version of the script into our SVN with a lot of positive feedback from Mac users. You can see my updated script here:
https://sourceforge.net/p/megamek/code/HEAD/tree/trunk/megamek/packaging_utils/JavaApplicationStub

**Comment by tofi86** [comment]
Thanks for your suggestions and contributions, @Dylan-M 

Next version will contain support for `JVMVersion` key. If a `JVMVersion` key is specified, the launcher tries to find this version without any fallback. If no suitable Java version can be found on the system, an error dialog is displayed:
![bildschirmfoto 2015-02-22 um 17 54 35](https://cloud.githubusercontent.com/assets/365118/6319419/1021d302-babc-11e4-8fae-11e9fe69c112.png)
The launcher script will not use a possible JVM fallback provided by `/usr/libexec/java_home` when finding no suitable version.

**Comment by Dylan-M** [comment]
If possible, you should probably add a comment that the plist entry is best with the + so that it will allow newer versions to support updates ;)
