### ISSUE TITLE
Internationalized messages

### ISSUE THREAD

**Issue by ebourg** [tofi86/universalJavaApplicationStub#27]
Hi,

It would be nice if the messages displayed by the stub could be internationalized. I'm providing a french translation if ever you manage to implement it.

> "Erreur au lancement de '${CFBundleName}'.\n\nLes versions de Java installées sur votre système ne conviennent pas.\nCe programme nécessite Java ${JVMVersion}.\nVeuillez installer la version de Java requise.\"

> "Erreur au lancement de '${CFBundleName}'.\n\n'MainClass' n'est pas spécifié!\nL'application Java ne peut pas être lancée.\"

> "Erreur au lancement de '${CFBundleName}'.\n\nJava doit être installé sur votre Mac.\nRendez-vous sur java.com pour les instructions d'installation...\"

**Comment by tofi86** [comment]
Thanks for your contribution, Emmanuel!

Unfortunately I've no idea how to localize apple script messages at the moment.
If someone has an idea and comes up with a pull request, I'd be happy to include this... :)

**Comment by ebourg** [comment]
I'm not a script expert, but maybe checking the LANG environment variable could work, something like this:

    if  [[ $LANG == fr* ]] ; then
        # french messages
        MESSAGE1="Erreur au lancement de '${CFBundleName}'"
        MESSAGE2="Java doit être installé sur votre Mac."
        MESSAGE3=...
        MESSAGE4=...
    elif  [[ $LANG == de* ]] ; then
        # german messages
        ...
    elif  [[ $LANG == es* ]] ; then
        # spanish messages
        ...
    else
        # english messages (default)
        MESSAGE1="ERROR launching '${CFBundleName}'"
        MESSAGE2="You need to have JAVA installed on your Mac!"
        MESSAGE3=...
        MESSAGE4=...
    fi

    osascript -e "tell application \"System Events\" to display dialog \"${MESSAGE1}\n\n${MESSAGE2}\" ...

**Comment by ebourg** [comment]
I experimented a bit and $LANG didn't work. I had to use:

    LANG=`defaults read -g AppleLocale`

I'll prepare a patch implementing this.

**Comment by tofi86** [comment]
Okay, great! :-)

**Comment by tofi86** [comment]
This is resolved on `develop` branch (after mergin your PR #30) and will be released with version 1.1.0 soon.

Thanks for your contribution. 😄 

I also
* added German localization
* adapted the changes from #28

**Comment by tofi86** [comment]
<img width="532" alt="bildschirmfoto 2016-07-04 um 22 12 13" src="https://cloud.githubusercontent.com/assets/365118/16569708/aa246036-4239-11e6-8ae9-e0daf0f6aed7.png">
<img width="532" alt="bildschirmfoto 2016-07-04 um 22 12 50" src="https://cloud.githubusercontent.com/assets/365118/16569709/aa2597da-4239-11e6-8b5e-071b7ca3c6b1.png">
<img width="532" alt="bildschirmfoto 2016-07-04 um 22 13 05" src="https://cloud.githubusercontent.com/assets/365118/16569710/aa4a64ac-4239-11e6-9391-95bd12b517e3.png">

**Comment by ebourg** [comment]
Thank you! Minor tweak for the french translation:

    MSG_JAVA_VERSION_OR_LATER="ou ultérieur"

**Comment by tofi86** [comment]
Fixed on `develop` branch. Thanks!

**Comment by tofi86** [comment]
This was fixed in version 2.0.0 released just today! Thanks for your contribution! 👏
