### ISSUE TITLE
Improve the version of Java reported in the error messages

### ISSUE THREAD

**Issue by ebourg** [tofi86/universalJavaApplicationStub#28]
When the version of Java installed doesn't match the version required by the application the following message is displayed:

> This program requires Java 1.8+

The message could mislead people into looking for Java 1.8 instead of Java 8. Developers usually know that 1.8 == 8, but end users can easily get confused. Also the '+' sign could be translated into "or later". So the ideal message would look like this:

> This program requires Java 8 or later

**Comment by tofi86** [comment]
Resolved in development version

**Comment by tofi86** [comment]
This has also been considdered in the localization feature (#27, #30)

**Comment by tofi86** [comment]
This was improved in version 2.0.0 released just today! Thanks for your contribution! 👏
