### ISSUE TITLE
Send to java.com when the version of Java installed is too old

### ISSUE THREAD

**Issue by ebourg** [tofi86/universalJavaApplicationStub#29]
The stub redirects to java.com when no version of Java is found, but not when the version installed is too old. If the application requires Java 1.x+ it's safe to present a button redirecting to java.com too.

**Comment by tofi86** [comment]
Jup, you're right. Scheduleing this for 1.1 release

**Comment by tofi86** [comment]
Resolved in development version

**Comment by Dylan-M** [comment]
I know this is closed as resolved, but it may be worth it to replace the automatic reload with a dialog box that mentions installing it via homebrew OR from java.com (with a link on the dialog)

**Comment by tofi86** [comment]
This was improved in version 2.0.0 released just today! Thanks for your contribution! 👏
