### ISSUE TITLE
Better search algorithm for specified Java version

### ISSUE THREAD

**Issue by tofi86** [tofi86/universalJavaApplicationStub#35]
From discussion in closed PR #34:

*@ebourg wrote:*
> Maybe a better approach would be to find all the Java runtime available and satisfying the version required in the plist file, and then picking the one with the highest Java version.

This would solve the problem with the current implementation of searching for a specific Java version (e.g. `1.6+`) picking the oldest (1.6) version instead of a newer version (e.g. JRE 1.8).

**Comment by tofi86** [comment]
To be more precise:

What we're currently doing is querying the `/usr/libexec/java_home` which already has an interface for picking a specific java version:

```
→ /usr/libexec/java_home -V
Matching Java Virtual Machines (5):
    1.8.0_91, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
    1.8.0_66, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home
    1.7.0_79, x86_64:	"Java SE 7"	/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home
    1.6.0_65-b14-468, x86_64:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
    1.6.0_65-b14-468, i386:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
```

Querying for `1.6+` would already pick the latest JDK 8:

```
→ /usr/libexec/java_home -v 1.6+
/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home
```

But now image this situation where only the old Apple Java is installed:

```
→ /usr/libexec/java_home -V
Matching Java Virtual Machines (2):
    1.6.0_65-b14-468, x86_64:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
    1.6.0_65-b14-468, i386:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
```

But the user has a copy of the Oracle Java 8 browser plugin installed in `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java`.
Unfortunately Oracle's new strategy is, that only JDK's register to `/usr/libexec/java_home` and JRE's don't. So querying for `/usr/libexec/java_home -v 1.6+` would return old Java 6 although the user has installed Oracle JRE 8.

**Comment by tofi86** [comment]
This is implemented on `develop` branch. @ebourg, can you please test the `develop` branch and tell me if that works for you?
I checked and tested a lot—I'd say it works for me :)

Since the bash on Mac OS X is v3 and cannot `declare -A` an associative key/value array, the approach for finding the highest matching java version is to first check `/usr/libexec/java_home -v XXX` and use this (because it always returns the latest matching java version) and only if the Oracle or Apple JRE plugins contain an even higher matching java version, this will be used.

Tests are passing with setup as described in the comment above.
Asking for `1.6+` in the above mentioned environment previously returned `/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home` from the `/usr/libexec/java_home -v 1.6+` and now returns `"/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java"` from the Oracle JRE plugin because I have JRE version 1.8.0_101 installed.

**Comment by tofi86** [comment]
Closing this now.

@ebourg: if you can test latest development version from `develop` branch and confirm that it's also working for you, that would be great. If not, this is going to be released in 1.1 as is.

**Comment by ebourg** [comment]
Thank you, I haven't got the time to test yet, I'll let you know if there is anything wrong.

**Comment by tofi86** [comment]
Thanks!
