### ISSUE TITLE
Add "Install Java from HomeBrew" button alongside with "Visit java.com" when Java is missing

### ISSUE THREAD

**Issue by tofi86** [tofi86/universalJavaApplicationStub#38]
Suggestion by @Dylan-M in #29:

> […] it may be worth it to replace the automatic reload with a dialog box that mentions installing it via homebrew OR from java.com (with a link on the dialog)

**Comment by tofi86** [comment]
I'm gonna put this in the backlog for now.
This is obviously only for professional users / tech geeks who have HomeBrew installed on theier system.

When displaying such a button, we should make sure in the first place, that the `brew` command is already installed.

**Comment by Dylan-M** [comment]
Well, I find homebrew the best thing since sliced bread in the Mac world, and I've even got a non-power user friend using it. Of course, that's only cause she can lean on me if she needs help. Regardless, thanks for the obvious thought you're putting into this.

**Comment by tofi86** [comment]
@Dylan-M will definately considder this for a next release! However, I just released version 2.0 without it because there are some issues with the installation process.
Imagine we have this AppleScript dialog with a button which tells us "Install Java from HomeBrew". But this process needs to take place on the commandline which isn't accessible at the moment so the user cannot see what's happening or wether there appear errors during the installation... I'm not sure how to handle this...

Also it seems to be quite tricky to add a variable button in AppleScript...

**Comment by Dylan-M** [comment]
My suggestion would be to just offer them a copy/paste to the command line rather than auto-installing it.

**Comment by tofi86** [comment]
Good idea! 👍

**Comment by Dylan-M** [comment]
Just checking back on this, as it's been awhile since I last checked in with this project :)

**Comment by tofi86** [comment]
Haven't worked on this yet, sorry...
However, PullRequests for an implementation of this feature are welcome ;-)

**Comment by Dylan-M** [comment]
PRs are the sweetness. I want more of those too ;)

So... I'll see if I can come up with something.

**Comment by tofi86** [comment]
With #78 I added a choice between Oracle and AdoptOpenJDK download buttons.

However, I decided not to add an "Install from Homebrew" button because for most end-users it's just too technical.
