### ISSUE TITLE
Do not expand folder/* classpath

### ISSUE THREAD

**Issue by mguessan** [tofi86/universalJavaApplicationStub#41]
UniversalJavaApplicationStub 2.0.1 expands defaults lib/* path instead of passing it directly to java command line.

DavMail relies on your script to replace old binary Java launchers, it works great except for this issue.
See https://sourceforge.net/p/davmail/support-requests/300/ for more details.

Patch moves variable expansion to all cases except OracleJavaFolder fallback.

**Comment by tofi86** [comment]
Fixed with version 2.0.2 with PR #42 by @mguessan.

Thanks!
