### ISSUE TITLE
Unsure of how to use this project

### ISSUE THREAD

**Issue by agastya3625** [tofi86/universalJavaApplicationStub#45]
Hi, 

I'm fairly new to bundling apps, so I'm sorry if these questions seem a bit redundant: 

1. I've downloaded the JarBundler-Master.zip file as well as the jarbundler-core-3.3.0.jar file. Are they the same/different? How are each of these files used?

2. Do I add the following code in my own build.xml file, or do I need other elements in that file as well?
<jarbundler
	name="Your-App"
	shortname="Your Application"
	icon="${resources.dir}/icon.icns"
	stubfile="${resources.dir}/universalJavaApplicationStub"
	useJavaXKey="true"
	... >
</jarbundler>

Thanks!

**Comment by tofi86** [comment]
You can have a look at one of my projects (older version where I was still using ANT instead of Maven for building my apps): https://github.com/paginagmbh/EPUB-Checker/blob/v1.6.1/build.xml#L111

This is how I configured the JarBundler task together wit this project.
