### ISSUE TITLE
More quoting issues

### ISSUE THREAD

**Issue by steve-in-ont** [tofi86/universalJavaApplicationStub#48]
Statements starting with:
`if [ -z ${JAVACMD} ]`
... will fail if the Java command path contains spaces. This should probably be changed to:
`if [ -z "${JAVACMD}" ]`
I count four such statements in the version 2.1.0 release.

**Comment by tofi86** [comment]
Good catch! You're absolutely right! Thanks for reporting this. I fixed it on `develop` branch and will release soon.

**Comment by tofi86** [comment]
This fix has been released with version 3.0.0 right now... Thanks for reporting it 👍
