### ISSUE TITLE
Unary operator error with Java 9

### ISSUE THREAD

**Issue by peterdell** [tofi86/universalJavaApplicationStub#52]
Hi,

line 312 need quotes around the first operand of the ==. Otherwise there is an error reporting unary operator on Mac OS X with Java 9.0.1, 64 bit

  if [ "${java_ver:0:2}" == "1." ] ; then

Regards, Peter.

**Comment by tofi86** [comment]
Hi Peter,
thanks for reporting this. I assume you used the latest version 2.1.0 from `master` branch, right?

Any chance you could test the new version from `develop` branch where I fixed a couple of bugs related to version number parsing and comparison? https://github.com/tofi86/universalJavaApplicationStub/milestone/6?closed=1

Does it work for you?

Best, Tobias

**Comment by sagecook** [comment]
FWIW: I made this same fix on my own in December and it works:
   if [ "${java_ver:0:2}" == "1." ] ; then

**Comment by sagecook** [comment]
I just tested with the develop version and this fix is moot.

**Comment by tofi86** [comment]
Great, thanks for testing the `develop` branch.

Closing this as fixed with the next 2.2 release (sorry, it's long overdue 😞 )

**Comment by tofi86** [comment]
This fix has been released with [version 3.0.0](https://github.com/tofi86/universalJavaApplicationStub/releases/tag/v3.0.0) right now... Thanks for reporting it 👍
