### ISSUE TITLE
Doesn't handle all JVM version numbers correctly

### ISSUE THREAD

**Issue by JohnLussmyer** [tofi86/universalJavaApplicationStub#61]
I just tried this with our app that used an older version of this script.
Even though we have a 1.8+ min JVM, it chose a 1.6vm.

note that for the jvms that have a build number, it's generating a 12 digit version to check, rather than an 8 digit one.
```
3/7/18 11:51:09.216 AM universalJavaApplicationStub[50607]: [50603][universalJavaApplicationStub] [StubDir] /Applications/EFI/Metrix/Metrix.app/Contents/MacOS
3/7/18 11:51:09.265 AM universalJavaApplicationStub[50617]: [50603][Metrix] [PlistStyle] Apple
3/7/18 11:51:09.406 AM universalJavaApplicationStub[50665]: [50603][Metrix] [JavaRequirement] JVM minimum version: 1.8+
3/7/18 11:51:09.413 AM universalJavaApplicationStub[50667]: [50603][Metrix] [JavaRequirement] JVM maximum version: 
3/7/18 11:51:09.531 AM universalJavaApplicationStub[50670]: [50603][Metrix] [Language] en_US
3/7/18 11:51:10.478 AM universalJavaApplicationStub[50682]: [50603][Metrix] [JavaSearch] Checking for $JAVA_HOME ...
3/7/18 11:51:10.486 AM universalJavaApplicationStub[50684]: [50603][Metrix] [JavaSearch] ... didn't found JAVA_HOME
3/7/18 11:51:10.494 AM universalJavaApplicationStub[50686]: [50603][Metrix] [JavaSearch] Checking for JavaVirtualMachines on the system ...
3/7/18 11:51:10.635 AM universalJavaApplicationStub[50715]: [50603][Metrix] [JavaSearch] ... found JVM: 1.8.0_111:/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java
3/7/18 11:51:10.643 AM universalJavaApplicationStub[50717]: [50603][Metrix] [JavaSearch] ... found JVM: 1.8.0_05:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/bin/java
3/7/18 11:51:10.651 AM universalJavaApplicationStub[50719]: [50603][Metrix] [JavaSearch] ... found JVM: 1.6.0_65-b14-468:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java
3/7/18 11:51:10.659 AM universalJavaApplicationStub[50721]: [50603][Metrix] [JavaSearch] ... found JVM: 1.6.0_65-b14-468:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java
3/7/18 11:51:10.666 AM universalJavaApplicationStub[50723]: [50603][Metrix] [JavaSearch] ... found JVM: 1.6.0_65:/Library/Java/Home/bin/java
3/7/18 11:51:10.675 AM universalJavaApplicationStub[50725]: [50603][Metrix] [JavaSearch] ... found JVM: 1.8.0_161:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
3/7/18 11:51:10.755 AM universalJavaApplicationStub[50783]: [50603][Metrix] [JavaSearch] ... ... matches all requirements: 08000111:1.8.0_111:/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java
3/7/18 11:51:10.762 AM universalJavaApplicationStub[50785]: [50603][Metrix] [JavaSearch] ... ... matches all requirements: 08000005:1.8.0_05:/Library/Java/JavaVirtualMachines/jdk1.8.0_05.jdk/Contents/Home/bin/java
3/7/18 11:51:10.769 AM universalJavaApplicationStub[50787]: [50603][Metrix] [JavaSearch] ... ... matches all requirements: 060006514468:1.6.0_65-b14-468:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java
3/7/18 11:51:10.777 AM universalJavaApplicationStub[50789]: [50603][Metrix] [JavaSearch] ... ... matches all requirements: 060006514468:1.6.0_65-b14-468:/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java
3/7/18 11:51:10.785 AM universalJavaApplicationStub[50791]: [50603][Metrix] [JavaSearch] ... ... matches all requirements: 08000161:1.8.0_161:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java
3/7/18 11:51:10.833 AM universalJavaApplicationStub[50795]: [50603][Metrix] [JavaCommand] '/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java'
3/7/18 11:51:10.957 AM universalJavaApplicationStub[50802]: [50603][Metrix] [JavaVersion] 1.6.0_65 / 060006514468
```

**Comment by JohnLussmyer** [comment]
I changed line 419 to:
	echo "$(printf '%02s' ${arr[0]})$(printf '%03s' ${arr[1]})$(printf '%.03s' ${arr[2]})"
and that seems to have fixed the issue.

**Comment by tofi86** [comment]
Hi John,

thanks for the report. This is indeed and error and I was able to reproduce it.

Would you mind helping me test my fix? Can you please restore the original script and leave line 419 as it was and instead replace line 415 with the following:

```
	local cleaned=$(echo "$1" | sed -E 's/^1\.//g;s/-b[0-9]+-[0-9]+$//g;s/[a-zA-Z+*\-]//g;s/_/./g')
```

This is the step where cleaning the version number string takes place and I think it's better to clean the string first instead of cutting it after 3 digits as you did.

Can you confirm that it works?

Best,
Tobias

**Comment by tofi86** [comment]
Resolved with version 3.0.1

**Comment by JohnLussmyer** [comment]
Thanks for the fix.

I've attached a slightly modified version of the fixed script - not sure if you are interested in the changes.

1) We added Italian and Spanish translations (but the translations were made with the older script, so don't have 2 of the strings translated.  Those will get picked up in our next translation pass in a month or 2.)

2) Added support for the user to add JVM options to the command line.

--

Bobcats and Cougars, oh my!  http://john.casadelgato.com/Pets

**Comment by tofi86** [comment]
Hi John,

thanks, but the attachment is missing. I think you cannot attach files when you use the GitHub Email reply feature.

I'm really looking forward to the Italien and Spanish translations, just send them as a PullRequest (or via file) when you're done translating the new values. Thanks!

What do you mean with `2)`? The user can create a properties file next to the app?

**Comment by JohnLussmyer** [comment]
On Thu Mar 15 11:09:25 PDT 2018 notifications@github.com said:
>I'm really looking forward to the Italien and Spanish translations, just send them as a PullRequest (or via file) when you're done translating the new values. Thanks!

Ok, I'll hope I can remember... :-)

>
>What do you mean with `2)`? The user can create a properties file next to the app?

Yup.  (well, sortof.  Right now I just support a simple 1 line text file to add to the command line.)


--

Tigers prowl and Dragons soar in my dreams...
