### ISSUE TITLE
Exec uses JVMOptions instead of JVMOptionsArr

### ISSUE THREAD

**Issue by tommyTT** [tofi86/universalJavaApplicationStub#69]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
An app bundle with JVMOptions containing $APP_ROOT placeholder won't start because the value isn't replaced and therefore the referenced directories and files can't be found by my java program. The log output however shows the correct values for the options.

**Steps to reproduce the issue/enhancement:**

1. Have a JVMOptions key that uses the $APP_ROOT placeholder (in my case an external configuration file that is contained in a directory outside the app bundle).
2. Start the bundle and it will use the value with the placeholder instead of replacing it.

**What is the expected behavior?**
The exec call to java uses the version of the JVM Options that have the $APP_ROOT value replaced with the actual path.

**What is the current behavior?**
The non-replaced value of the JVM Options is given to the java exec call, although the log output shows the correct version.

**Do you have screenshots, GIFs, demos or samples which demonstrate the problem or enhancement?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- universalJavaApplicationStub version: 3.0.3
- Mac OS version: 10.13.5 (High Sierra)
- Java version(s): 1.8.0_172

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)
Change the variable used [here](https://github.com/tofi86/universalJavaApplicationStub/blob/master/src/universalJavaApplicationStub#L770) from JVMOptions to JVMOptionsArr.

**Comment by tofi86** [comment]
Thanks for your detailed report! Good catch, this is indeed a bug. I will fix it as soon as possible, I'm currently off for vacation for a week 🏖 😎

**Comment by tofi86** [comment]
This has been fixed with d0e100b and released as v3.0.4.

Thanks for reporting the issue! :-)
