### ISSUE TITLE
Use a bundled JRE inside the app-package as java executable

### ISSUE THREAD

**Issue by gravelld** [tofi86/universalJavaApplicationStub#7]
I was under the impression that having `CFBundleExecutable` point to this script would be enough; that it would be able to pick up a JRE from the app bundle and run it.

However, if I double click the app I still get the message that there's no Java 6 installed in Yosemite. Is there something else in the app bundle that I'm overlooking?

Note that manually executing universalJavaApplicationStub on the command line _does_ work.

**Comment by tofi86** [comment]
Note: this may be resolved with PR #26 in version 1.1

**Comment by tofi86** [comment]
This is solved now by PR #26 by using a relative path for `$JAVA_HOME` with the `<LSEnvironment>` Plist dictionary key.

Will be released with version 2.0 today.
