### ISSUE TITLE
Support runtimes from AdoptOpenJDK

### ISSUE THREAD

**Issue by treaves** [tofi86/universalJavaApplicationStub#71]
I'm submitting a…

- [ ] bug report
- [x] feature request
- [ ] other

**Short description of the issue/suggestion:**
Support runtimes from adoptopenjdk

**Steps to reproduce the issue/enhancement:**
I'm pulling down a runtime using their api from https://api.adoptopenjdk.net/v2/binary/nightly/openjdk11?openjdk_impl=hotspot&os=mac&arch=x64&release=latest&type=jre

**What is the expected behavior?**
The bundled runtime is found and used

**What is the current behavior?**

The bundled runtime is not found and used

**Do you have screenshots, GIFs, demos or samples which demonstrate the problem or enhancement?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- universalJavaApplicationStub version:
- Mac OS version:
- Java version(s):

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by tofi86** [comment]
Do you know where the AdoptOpen JDK is installed in the system?

What is the output of `/usr/libexec/java_home -V` after you install the AdoptOpen JDK?

**Comment by treaves** [comment]
It's download via API for bundling purpose, not installed in the system.  The particular bundler I (attempting) to use puts it MyApp.app/Contents/PlugIns/jre_x64 .

**Comment by tofi86** [comment]
Sorry, it's been a while.

As stated in the `README.md` file of this repository, you can use the environment variable `$JAVA_HOME` to use a bundled Java Runtime inside your app:

> There is some *foo* happening to determine which Java versions are installed – here's the list in which order system properties are checked:
> 
> 1. System variable `$JAVA_HOME`
>    * can also be set to a relative path using the [`<LSEnvironment>` Plist dictionary key](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/20001431-106825)
>      * which allows for bundling a custom version of Java inside your app!

However, I've never used it myself. But I think you can use the `<LSEnvironment>` Plist dictionary key to set `$JAVA_HOME` when starting your app.

Further details can be found here: https://github.com/tofi86/universalJavaApplicationStub/pull/26#issuecomment-444249836

Maybe you can use something like this:

```
<key>LSEnvironment</key>
<dict>
    <key>JAVA_HOME</key>
    <string>Contents/PlugIns/jre_x64/</string>
</dict>
```

The path must for sure be relative to the App root and the directory must be a valid java home dir (e.g. containing the bin/  directory, etc.).

Let me know if that works for you! :-)

**Comment by treaves** [comment]
The issue is this product expects there to be a JRE; there no longer are JRE's.  Starting with JDK10, they have been removed from Java.

**Comment by tofi86** [comment]
Which product expects a JRE? The `universalJavaApplicationStub`? It supports both JRE and JDK in the default locations installed in the system and it supports JRE and JDK bundled in the App.

**Comment by tofi86** [comment]
Closing this as invalid because bundling a AdoptOpen JDK or JRE workes. I just tested and explained the way to go in https://github.com/tofi86/universalJavaApplicationStub/pull/26#issuecomment-562990269
