### ISSUE TITLE
Arguments not passed correctly

### ISSUE THREAD

**Issue by robbyn** [tofi86/universalJavaApplicationStub#76]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
Arguments not passed correctly to the main method.

Specify arguments in the Info.plist:

...

>         <key>Arguments</key>
>         <array>
>             <string>-full</string>
>             <string>-manager</string>
>             <string>-slide-show</string>
>         </array>
> 

...

You would expect to receive the arguments:

> -full
> -manager
> -slide-show
> 

But you're actually receiving:

> Array
> {
> -full
> -manager
> -slide-show
> }
> 

- universalJavaApplicationStub version: 3.0.4
- Mac OS version: 10.14.6
- Java version(s): 11

**Comment by tofi86** [comment]
Thanks for the report. I was able to reproduce the issue and will commit a fix.

**Comment by tofi86** [comment]
I pushed a fix to the `develop` branch. Can you please check and try if it works for you?

Just a note for future readers: **Spaces in Arguments must be escaped!**

```xml
    <key>Arguments</key>
    <array>
        <string>-full</string>
        <string>"a value with spaces"</string>
    </array>
```
