### ISSUE TITLE
Question: File encoding

### ISSUE THREAD

**Issue by peterdell** [tofi86/universalJavaApplicationStub#89]
Hello Tobias,

I found that the latest version of the universalJavaApplicationStub script now contains non-ASCII characters fo the simplified Chinese location. The question is, therefore which encoding should be used to store/edit the file. Or maybe it would be possible to use bas64 encoded texts, so the source still remains ASCII-only.

Best regards, Peter.
![Encoding](https://user-images.githubusercontent.com/10855380/89898377-e3d89280-dbe0-11ea-8c0e-c1590aafe7de.png)

**Comment by tofi86** [comment]
The file is UTF-8 encoded and should be edited and saved as such. It's the standard for encoding Unicode characters and is supported by Eclipse as well. Just change the encoding for the file in the eclipse properties or – even better – change your eclipse project to use utf-8 file encodings to avoid the cp1252 encoding issue.

I'm sorry but I'm not going to change the file encoding or base64 encode non-ascii characters...

**Comment by peterdell** [comment]
Hello Tobias,

I'm not familiar with github rules and how exactly bash behaves on Mac OS X, but wouldn't it make sense to store the file with a correct UTF-8 byte order mark then?

Best regards; Peter.
