### ISSUE TITLE
ClassNotFoundException for org.eclipse.core.runtime.CoreException

### ISSUE THREAD

**Issue by peterdell** [tofi86/universalJavaApplicationStub#90]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [x] other

**Short description of the issue/suggestion:**
I have created a bundle, it does not start on Mac OS x.

**Steps to reproduce the issue/enhancement:**

1. [First Step]
Download the attached .zip files with the bundle.
2. [Second Step]
Start the app or run the univeralJavaApplicationStub or run java - Contents/Resources/Java/JavaHexEditor.jar
3. [Other Steps...]

**What is the expected behavior?**
The app should start

**What is the current behavior?**
It exits with "ClassNotFoundException" for org.eclipse.core.runtime.CoreException.

**Do you have screenshots, GIFs, demos or samples which demonstrate the problem or enhancement?**
Examples are attached.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- universalJavaApplicationStub version: 3.6.0
- Mac OS version: 10.13.6
- Java version(s): java SE 9.0.1, 64 bit sever

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)
You can find my complete sources and build scripts here.
https://sourceforge.net/p/javahexeditor/git/ci/master/tree/javahexeditor.standalone/build/

Best regards, Peter.
[javahexeditor-macosx-x86_64.zip](https://github.com/tofi86/universalJavaApplicationStub/files/5057328/javahexeditor-macosx-x86_64.zip)
[javahexeditor-macosx-x86.zip](https://github.com/tofi86/universalJavaApplicationStub/files/5057329/javahexeditor-macosx-x86.zip)

**Comment by tofi86** [comment]
Hi Peter,

thanks for your report. I'm currently on vacation and will take a look in 2 weeks once I'm back. Please stay tuned... :)

**Comment by peterdell** [comment]
Hi Tobias,

thanks for the heads-up, enjoy your vacation :-)

**Comment by peterdell** [comment]
I found that the problem as due to an older bug in the "https://github.com/eclipse/eclipse.jdt.ui/blob/6735e7a7f22b1e51d7f20bce4780e216485a5332/org.eclipse.jdt.ui/jar-in-jar-loader.zip" which didn't resolve correction under MacOS (but worked under Windows).

With this, I've managed to build my "ultimate Java to Windows/MacOS/Linux" ANT script (using laun4j, jarbundler, universalJavaApplicationStub)  plus a HelloWorld Example with diagnostic output.

https://github.com/peterdell/wudsn-base/tree/master/com.wudsn.tools.base.standalone
https://github.com/peterdell/wudsn-base/tree/master/com.wudsn.tools.base.hello.standalone

	<target name="all">

		<property name="applicationFolder" location=".." />
		<property name="applicationName" value="Hello" />
		<property name="applicationNameLowerCase" value="hello" />
		<property name="applicationTitle" value="Hello Standalone" />
		<property name="applicationSupportURL" value="https://www.wudsn.com" />
		<property name="applicationHeaderType" value="console" />
		<property name="applicationMainClass" value="com.wudsn.tools.base.hello.Hello" />
		<property name="applicationBinFolder" location="../bin" />
		<property name="applicationPlatformTextFile" location="${applicationBinFolder}/com/wudsn/tools/base/hello/Hello.os"/>
		<property name="iconFilePath" value="C:\jac\system\Java\Programming\Repositories\WUDSN-Base\com.wudsn.tools.base.standalone\icons\application.ico" />
		<property name="authors" value="Peter Dell" />
		<property name="releaseYears" value="2019 - 2020" />
		<property name="release" value="0.1.2" />
		<property name="version" value="Test" />

		<property name="jreMinVersion" value="1.8.0" />

		<ant dir="..\..\com.wudsn.tools.base.standalone\build" antfile="Makefile.ant" target="create_standalone_executables">

		</ant>
	</target>

Thanks again for providing the stub, tomorrow I'll have it tested on macOS Catalina etc.

Note: The documentation/doc links are broken, so in the end, I directly checked the task source. So if you find the time, updating the docs would be great!

Best regards, Peter.
