### ISSUE TITLE
/usr/libexec/java_home output format changed in macOS 11.0 (Big Sur)

### ISSUE THREAD

**Issue by duanhairuo** [tofi86/universalJavaApplicationStub#91]
<img width="592" alt="WX20200827-224242@2x" src="https://user-images.githubusercontent.com/7644567/91457730-43a88c00-e8b7-11ea-99b0-0a2e91ff4473.png">
如图

**Comment by tofi86** [comment]
Could you please open the `Console` app on macOS, filter for `syslog` and then start your App again? There should be some log messages for your JD-GUI app which will help me finding the issue.

Select them all and copy them here.

**Comment by tofi86** [comment]
Can you please post the output of the following command in terminal: `/usr/libexec/java_home -V`

Thanks.

**Comment by duanhairuo** [comment]
1. syslog

com.apple.xpc.launchd[1] (application.jd.jd-gui.31330448.31330457[38849]): Service exited with abnormal code: 3
2./usr/libexec/java_home -V

Matching Java Virtual Machines (1):
    1.8.0_261 (x86_64) "Oracle Corporation" - "Java SE 8" /Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home
/Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home

**Comment by duanhairuo** [comment]
my system version is mac big sur (11.0 Beta版(20A5354i))

**Comment by duanhairuo** [comment]
universalJavaApplicationStub version is 3.0.6

**Comment by jeremyhu** [comment]
The issue here is that the stub is using `java_home -V` which changed format in the rewrite in Big Sur.  If you want to get the raw data, you should use `java_home --xml`

**Comment by tofi86** [comment]
@jeremyhu yep, I also noticed that in the same moment in another support case... Thanks!

Will change the regex matchers in the first place and maybe do a rewrite to read from `java_home --xml` after that...

**Comment by tofi86** [comment]
Have been playin' around with the XML output a little bit and I think I'll go with this right away.

Although it will need some hacks to get `Plistbuddy` work on the XML structure... :-/

**Comment by tofi86** [comment]
Alright, I implemented a solution for parsing the XML output: aef096d

It's 40-70ms slower than the old solution but it should be more robust against future changes in the `java_home -V` CLI output.

Any chance you @duanhairuo or @jeremyhu could test on mac OS 11.0 Big Sur? I haven't upgraded to the beta yet...

**Comment by duanhairuo** [comment]
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin

**Comment by duanhairuo** [comment]
i delete /Library/Internet Plug-Ins/JavaAppletPlugin.plugin

**Comment by duanhairuo** [comment]
now i recover it ,work ok

**Comment by tofi86** [comment]
Glad it works for you. Please let the issue open. I'm still working on macOS 11 support.

**Comment by tofi86** [comment]
I have another user which contacted me via mail who tested the changes and reported it works on macOS Big Sur. I'm closing this and will work on releasing v3.1.0

**Comment by duanhairuo** [comment]
I delete /Library/Internet Plug-Ins/JavaAppletPlugin.plugin
Cancel any Java environment variable configuration on my Mac (big sur)
use the version of 3.1.0-beta  can work OK
so now i used it
Thinks!

**Comment by tofi86** [comment]
I've just tested this myself on macOS 11.0 "Big Sur" and the current `develop` version works.

Going to release this soon!

**Comment by tofi86** [comment]
Version 3.1.0 has officially been released 🎉

Details: https://github.com/tofi86/universalJavaApplicationStub/releases/tag/v3.1.0

Note: The release now also contains compiled binaries which seem to be necessary in macOS 11.0 "Big Sur" and later...

**Comment by DerekCook** [comment]
Hi. 

Apologies if I am raising this query in the wrong place, but I cannot find a general way to ask a Q without raising an issue, and I only have a query, not an issue. :-)

I recently moved to Big Sur a few months back and noticed my apps were no longer working, but have had no time since then to investigate further (other than I noticed it would still work if you used the console OPEN command!). But good to see this has been fixed - I have tried the new compiled binary quickly tonight in my apps, and it looks good.

However one thing I wanted to ask is that I noticed on the release page that you have binaries for both 10.15 and 11.0. Does this mean that depending on my users OS version, I may need to install a specific version? Unfortunately I don't really have a way of checking given I have migrated to Big Sur.

**Comment by tofi86** [comment]
> Apologies if I am raising this query in the wrong place, but I cannot find a general way to ask a Q without raising an issue, and I only have a query, not an issue. :-)

I just recently activated GitHub Discussions for those kinds of questions :-)
https://github.com/tofi86/universalJavaApplicationStub/discussions

However, your question came earlier so I'm happy to answer it here...

> Does this mean that depending on my users OS version, I may need to install a specific version?

Yes, that's indeed the gist of the discussion in #85. The compiled binary for 10.5 *may* work in 11.0, but I wouldn't bet on it. However, the compiled binary for 11.0 will definitely **not work** on earlier macOS versions.

That's problematic, even for my own apps. Therefore I choose to stick with the uncompiled version for the moment as I don't need special macOS entitlements (like accessing special folders, etc.).

**Comment by DerekCook** [comment]
Thanks, I will start a discussion then. :)
