### ISSUE TITLE
Expand Variables JVMOptions and JVMDefaultOptions

### ISSUE THREAD

**Issue by najdanovicivan** [tofi86/universalJavaApplicationStub#99]
I'm submitting a…

- [ ] bug report
- [x] feature request
- [ ] other

**Short description of the issue/suggestion:**
Expand variables $APP_PACKAGE, $JAVAROOT, $USER_HOME into JVMOptions and JVMDefaultOptions

**What is the motivation / use case for changing the behavior?**
This is relate to bug https://bugs.openjdk.java.net/browse/JDK-8255877
I'm building the app with custom PKCS#11 Middleware and I need to embed the dylib inside the bundle

**Comment by tofi86** [comment]
Hi @najdanovicivan, thanks for your feature request. I added this with ba80b38 on `develop` branch and you can test it if you like...
